wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.6
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.15
    start_time: 1679571129.965588
    t:
      1:
      - 2
      - 3
      - 5
      - 53
      - 55
      2:
      - 2
      - 3
      - 5
      - 53
      - 55
      3:
      - 2
      - 19
      - 23
      - 37
      4: 3.9.15
      5: 0.13.6
      8:
      - 1
      - 3
      - 5
activation_fn:
  desc: null
  value: SELU
architecture_name:
  desc: null
  value: LSTM_AE
batch_size:
  desc: null
  value: 178
dataset_name:
  desc: null
  value: Kenya_90k_Set_1_w90
epochs:
  desc: null
  value: 100
latent_layer_size:
  desc: null
  value: 25
learning_rate:
  desc: null
  value: 0.0011407659150172015
optimizer:
  desc: null
  value: nadam
window_length:
  desc: null
  value: 90
