wandb_version: 1

activation_fn:
  value: LeakyReLU
batch_size:
  value: 188
epochs:
  value: 100
latent_layer_size:
  value: 25
learning_rate:
  value: 0.002546666057731362
optimizer:
  value: nadam
window_length:
  value: 90
