wandb_version: 1

activation_fn:
  value: LeakyReLU
batch_size:
  value: 286
epochs:
  value: 100
latent_layer_size:
  value: 25
learning_rate:
  value: 0.0018024342887116072
optimizer:
  value: nadam
window_length:
  value: 90
