wandb_version: 1

activation_fn:
  value: LeakyReLU
batch_size:
  value: 130
epochs:
  value: 100
latent_layer_size:
  value: 25
learning_rate:
  value: 8.171579676021561e-05
optimizer:
  value: nadam
window_length:
  value: 90
