wandb_version: 1

activation_fn:
  value: LeakyReLU
batch_size:
  value: 220
epochs:
  value: 100
latent_layer_size:
  value: 25
learning_rate:
  value: 0.00035666979555446833
optimizer:
  value: nadam
window_length:
  value: 90
