wandb_version: 1

activation_fn:
  value: LeakyReLU
batch_size:
  value: 124
epochs:
  value: 100
latent_layer_size:
  value: 25
learning_rate:
  value: 2.280161894256291e-05
'lr_decay:':
  value: 0.01
optimizer:
  value: nadam
window_length:
  value: 90
